### ISSUE TITLE
all options can be added in a single line at nvidia-xconfig

### ISSUE THREAD

**Issue by cjclm7** [the-codepunker/ubuntu-nvidia-mining#1]
Suggestion (not an issue), on the step by step guide, the steps 12. 15. 16 can be all executed in a single command:

`sudo nvidia-xconfig --enable-all-gpus --cool-bits=31 --allow-empty-initial-configuration --connected-monitor=DFP-0 --custom-edid=DFP-0:/etc/X11/dfp0.edid`

**Comment by the-codepunker** [comment]
That's correct. You can submit a pull request if you want. I will gladly merge it but please also keep the step by step option.
