### ISSUE TITLE
AMD mixing

### ISSUE THREAD

**Issue by jamborloi** [the-codepunker/ubuntu-nvidia-mining#3]
Hi, 
Your tutorial is very good. Just starting to mine with some NVIDIA GPUs.
Although your tutorial is only for NVIDIA and done your overclocking procedure.
I have one more slot and put a AMD RX580 on it and install AMD drivers.
ethminer works but with nvidia cards only then I put the option -X instead of -U. It works only with my NVIDIAs.
So I tried Claymore dual eth miner but it only detects the nvidia.
If I check with :~$ lspci | grep VGA
I can detect AMD/ATI card on this command.

Then I tried the occ.sh manually I can get 2753 segmentation fault (core dumped) DISPLAY=0  for fan control gpu hz and memory.

Can I fix it and run together with AMD and NVIDIA?

Regards,

**Comment by the-codepunker** [comment]
@jamborloi I have never tested AMD cards on this setup so I can't help with this issue.

**Comment by jamborloi** [comment]
@the-codepunker 
Thank you for your reply.
I think there is a problem on installing both AMD and NVIDIA drivers that is why I got those error. Anyway I will not try to mix AMD and NVIDIA GPU on mining.
